# Generated by Django 6.0.3 on 2026-03-31 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('christening', 'Christening'), ('anniversary', 'Anniversary'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cakes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('christening', 'Christening'), ('kids_birthday', "Kid's Birthday"), ('adults_party', "Adult's Party"), ('wedding', 'Wedding'), ('corporate', 'Corporate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(blank=True, help_text='List features, one per line')),
                ('included_items', models.TextField(blank=True, help_text='List included items, one per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('shape', models.CharField(blank=True, default='Round', max_length=50)),
                ('flavor', models.CharField(blank=True, default='Chocolate', max_length=50)),
                ('frosting', models.CharField(blank=True, default='Buttercream', max_length=50)),
                ('filling', models.CharField(blank=True, max_length=50)),
                ('color_palette', models.CharField(blank=True, max_length=100)),
                ('message_on_cake', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hanilies.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CakeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_on_cake', models.CharField(blank=True, max_length=200)),
                ('color_palette', models.CharField(blank=True, max_length=100)),
                ('design_reference', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('additional_decorations', models.TextField(blank=True)),
                ('cake_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='hanilies.cakeorder')),
            ],
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('event_type', models.CharField(choices=[('christening', 'Christening'), ('kids_birthday', "Kid's Birthday"), ('adults_party', "Adult's Party"), ('wedding', 'Wedding'), ('corporate', 'Corporate')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue', models.TextField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('selected_addons', models.TextField(blank=True)),
                ('cake_flavor', models.CharField(blank=True, max_length=50)),
                ('cake_frosting', models.CharField(blank=True, max_length=50)),
                ('cake_filling', models.CharField(blank=True, max_length=50)),
                ('cake_message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hanilies.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cake_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hanilies.cakeorder')),
                ('package_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hanilies.packageorder')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner - Full Access'), ('admin', 'Admin - All Management'), ('manager', 'Manager - Orders & Customers'), ('baker', 'Baker - Cake Management'), ('packager', 'Packager - Package Management'), ('cashier', 'Cashier - Payments Only'), ('viewer', 'Viewer - Read Only')], default='viewer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
