# Generated by Django 6.0.3 on 2026-05-29 00:00

from django.db import migrations, models


def remove_corporate_package_records(apps, schema_editor):
    Package = apps.get_model('hanilies', 'Package')
    PackageOrder = apps.get_model('hanilies', 'PackageOrder')
    Payment = apps.get_model('hanilies', 'Payment')
    ActivityLog = apps.get_model('hanilies', 'ActivityLog')

    package_ids = list(
        Package.objects.filter(package_type='corporate').values_list('id', flat=True)
    )
    order_ids = list(
        PackageOrder.objects.filter(event_type='corporate').values_list('id', flat=True)
    )

    if package_ids:
        order_ids.extend(
            PackageOrder.objects.filter(package_id__in=package_ids).values_list('id', flat=True)
        )

    order_ids = list(set(order_ids))

    payment_ids = []
    if order_ids:
        payment_ids = list(
            Payment.objects.filter(package_order_id__in=order_ids).values_list('id', flat=True)
        )

    if package_ids:
        ActivityLog.objects.filter(
            target_type='package',
            target_id__in=package_ids,
        ).delete()

    if order_ids:
        ActivityLog.objects.filter(
            target_type='package_order',
            target_id__in=order_ids,
        ).delete()

    if payment_ids:
        ActivityLog.objects.filter(
            target_type='payment',
            target_id__in=payment_ids,
        ).delete()

    if order_ids:
        PackageOrder.objects.filter(id__in=order_ids).delete()

    if package_ids:
        Package.objects.filter(id__in=package_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0003_activitylog'),
    ]

    operations = [
        migrations.RunPython(
            remove_corporate_package_records,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(
                choices=[
                    ('christening', 'Christening'),
                    ('kids_birthday', "Kid's Birthday"),
                    ('adults_party', "Adult's Party"),
                    ('wedding', 'Wedding'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('christening', 'Christening'),
                    ('kids_birthday', "Kid's Birthday"),
                    ('adults_party', "Adult's Party"),
                    ('wedding', 'Wedding'),
                ],
                max_length=20,
            ),
        ),
    ]