# Generated by Django 6.0.3 on 2026-05-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0004_remove_corporate_package_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(
                choices=[
                    ('birthday', 'Birthday'),
                    ('wedding', 'Wedding'),
                    ('christening', 'Christening'),
                    ('anniversary', 'Anniversary'),
                    ('custom', 'Special Occasions'),
                ],
                max_length=20,
            ),
        ),
    ]