# Generated by Django 6.0.3 on 2026-05-29 00:45

from django.db import migrations


def replace_graduation_theme(apps, schema_editor):
    CakeOrder = apps.get_model('hanilies', 'CakeOrder')
    CakeOrder.objects.filter(theme='Graduation').update(
        theme='Special Occasions'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0005_rename_custom_cake_label'),
    ]

    operations = [
        migrations.RunPython(
            replace_graduation_theme,
            migrations.RunPython.noop,
        ),
    ]