# Generated by Django 6.0.3 on 2026-05-29 01:10

from decimal import Decimal

from django.db import migrations


SPECIAL_OCCASION_CAKES = [
    (17, "Valentine's Day Cake", "Romantic cake design for Valentine's Day celebrations.", Decimal('1200.00')),
    (18, "Mother's Day Cake", "Floral celebration cake crafted for Mother's Day.", Decimal('850.00')),
    (19, "Father's Day Cake", "Bold celebration cake made for Father's Day gatherings.", Decimal('900.00')),
    (20, 'Graduation Cake', 'Milestone cake designed for graduation celebrations.', Decimal('1300.00')),
    (21, 'Debut Cake', 'Elegant debut cake for 18th birthday and formal milestone events.', Decimal('1400.00')),
    (22, 'Gender Reveal Cake', 'Celebration cake for surprise gender reveal moments.', Decimal('1250.00')),
    (23, "Teachers' Day Cake", "Appreciation cake prepared for Teachers' Day events.", Decimal('950.00')),
    (24, 'Christmas Cake', 'Festive cake styled for Christmas gatherings and gift tables.', Decimal('1000.00')),
    (25, 'New Year Cake', 'Sparkling celebration cake for New Year parties.', Decimal('950.00')),
]


def seed_special_occasion_cakes(apps, schema_editor):
    Cake = apps.get_model('hanilies', 'Cake')

    for cake_id, name, description, price in SPECIAL_OCCASION_CAKES:
        Cake.objects.update_or_create(
            pk=cake_id,
            defaults={
                'name': name,
                'category': 'custom',
                'description': description,
                'price': price,
                'stock': 3,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0006_remove_graduation_theme'),
    ]

    operations = [
        migrations.RunPython(
            seed_special_occasion_cakes,
            migrations.RunPython.noop,
        ),
    ]