# Generated by Django 6.0.3 on 2026-05-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0007_seed_special_occasion_cakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/thumbnails/')),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='hanilies.package')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [
                    models.UniqueConstraint(fields=('package', 'sort_order'), name='unique_package_thumbnail_slot'),
                ],
            },
        ),
    ]