# Generated by Django 6.0.3 on 2026-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0015_generated_order_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('payment_retry', 'Awaiting Payment Resubmission'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('payment_retry', 'Awaiting Payment Resubmission'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Under Verification'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner - Full Access'), ('admin', 'Admin - All Management'), ('manager', 'Manager - Full Management Access'), ('supervisor', 'Supervisor - Full Management Access'), ('baker', 'Baker - Cake Management'), ('packager', 'Packager - Package Management'), ('cashier', 'Cashier - Payments and Products'), ('customer', 'Customer - Customer Portal')], default='customer', max_length=20),
        ),
    ]
