# Generated by Django 6.0.3 on 2026-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0017_product_customization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='design_reference',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
