# Generated by Django 6.0.3 on 2026-07-06 22:30

from django.db import migrations, models


def populate_product_codes(apps, schema_editor):
    Cake = apps.get_model('hanilies', 'Cake')
    Package = apps.get_model('hanilies', 'Package')

    for cake in Cake.objects.filter(product_code__isnull=True).order_by('id'):
        cake.product_code = f'CK-{cake.id:04d}'
        cake.save(update_fields=['product_code'])

    for package in Package.objects.filter(product_code__isnull=True).order_by('id'):
        package.product_code = f'PKG-{package.id:04d}'
        package.save(update_fields=['product_code'])


def clear_product_codes(apps, schema_editor):
    Cake = apps.get_model('hanilies', 'Cake')
    Package = apps.get_model('hanilies', 'Package')

    Cake.objects.update(product_code=None)
    Package.objects.update(product_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0018_packageorder_design_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='product_code',
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='product_code',
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(populate_product_codes, clear_product_codes),
    ]
