# Generated by Django 6.0.3 on 2026-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0022_homestripimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('christening', 'Christening'), ('kids_birthday', "Kid's Birthday"), ('adults_party', 'Adult Birthday Party'), ('wedding', 'Wedding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='event_type',
            field=models.CharField(choices=[('christening', 'Christening'), ('kids_birthday', "Kid's Birthday"), ('adults_party', 'Adult Birthday Party'), ('wedding', 'Wedding')], max_length=20),
        ),
    ]
