# Generated by Django 6.0.3 on 2026-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0026_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
