# Generated by Django 6.0.3 on 2026-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0027_contactinquiry_is_read_contactinquiry_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('story', 'Our Story Image'), ('team_teresa', 'Teresa Rabillas Team Image'), ('team_maria', 'Maria Santos Team Image'), ('team_john', 'John Reyes Team Image'), ('team_anna', 'Anna Lim Team Image')], max_length=40, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
