# Generated by Django 6.0.3 on 2026-07-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0028_aboutpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageimage',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aboutpageimage',
            name='display_position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aboutpageimage',
            name='image_position',
            field=models.CharField(choices=[('center center', 'Center'), ('center top', 'Top'), ('center bottom', 'Bottom'), ('left center', 'Left'), ('right center', 'Right'), ('left top', 'Top Left'), ('right top', 'Top Right'), ('left bottom', 'Bottom Left'), ('right bottom', 'Bottom Right')], default='center center', max_length=24),
        ),
    ]
