# Generated by Django 6.0.3 on 2026-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0030_contactinquiry_admin_reply_contactinquiry_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorder',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
