from django.urls import path
from . import views

urlpatterns = [
    # Main site pages
    path('', views.home, name='home'),
    path('cakes/', views.cakes, name='cakes'),
    path('packages/', views.packages, name='packages'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('new-demo-bot/config/', views.new_demo_bot_config,
         name='new_demo_bot_config'),
    path('new-demo-bot/session/', views.new_demo_bot_session,
         name='new_demo_bot_session'),

    # Authentication
    path('login/', views.login_view, name='login'),
    path('forgot-password/',
         views.HaniliesPasswordResetRequestView.as_view(), name='password_reset'),
    path('forgot-password/done/',
         views.HaniliesPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         views.HaniliesPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),

    # User pages
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('update-preferences/', views.update_preferences,
         name='update_preferences'),
    path('order-tracking/', views.order_tracking, name='order_tracking'),
    path('order-tracking/<str:order_type>/<int:order_id>/print/',
         views.order_tracking_print, name='order_tracking_print'),
    path('order-tracking/<str:order_type>/<int:order_id>/testimonial/',
         views.submit_testimonial, name='submit_testimonial'),
    path('order-tracking/<str:order_type>/<int:order_id>/payments/<int:payment_id>/resubmit/',
         views.resubmit_payment_proof, name='resubmit_payment_proof'),
    path('order-cancel/<str:order_type>/<int:order_id>/',
         views.request_order_cancellation, name='request_order_cancellation'),

    # Order pages
    path('cake-customize/', views.cake_customize, name='cake_customize'),
    path('payment-qr-preview/', views.payment_qr_preview,
         name='payment_qr_preview'),
    path('order-package/', views.package_order, name='order_package'),
    path('package-order/', views.package_order, name='package_order'),
    path('package-cake-customize/', views.package_cake_customize,
         name='package_cake_customize'),
    path('package-payment/', views.package_payment, name='package_payment'),

    # Custom Admin Panel
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/home-hero/', views.admin_home_hero_images,
         name='admin_home_hero_images'),
    path('admin-panel/home-hero/add/', views.admin_home_hero_add,
         name='admin_home_hero_add'),
    path('admin-panel/home-hero/edit/<int:hero_image_id>/',
         views.admin_home_hero_edit, name='admin_home_hero_edit'),
    path('admin-panel/home-hero/delete/<int:hero_image_id>/',
         views.admin_home_hero_delete, name='admin_home_hero_delete'),
    path('admin-panel/home-strip/', views.admin_home_strip_images,
         name='admin_home_strip_images'),
    path('admin-panel/home-strip/add/', views.admin_home_strip_add,
         name='admin_home_strip_add'),
    path('admin-panel/home-strip/edit/<int:strip_image_id>/',
         views.admin_home_strip_edit, name='admin_home_strip_edit'),
    path('admin-panel/home-strip/delete/<int:strip_image_id>/',
         views.admin_home_strip_delete, name='admin_home_strip_delete'),
    path('admin-panel/about-images/', views.admin_about_images,
         name='admin_about_images'),
    path('admin-panel/about-images/edit/<int:image_id>/',
         views.admin_about_image_edit, name='admin_about_image_edit'),
    path('admin-panel/cakes/', views.admin_cakes, name='admin_cakes'),
    path('admin-panel/cakes/add/', views.admin_cake_add, name='admin_cake_add'),
    path('admin-panel/cakes/edit/<int:cake_id>/',
         views.admin_cake_edit, name='admin_cake_edit'),
    path('admin-panel/cakes/bulk-action/',
         views.admin_cakes_bulk_action, name='admin_cakes_bulk_action'),
    path('admin-panel/cakes/delete/<int:cake_id>/',
         views.admin_cake_delete, name='admin_cake_delete'),
    path('admin-panel/cake-orders/',
         views.admin_cake_orders, name='admin_cake_orders'),
    path('admin-panel/cake-orders/bulk-action/',
         views.admin_cake_orders_bulk_action, name='admin_cake_orders_bulk_action'),
    path('admin-panel/cake-orders/view/<int:order_id>/',
         views.admin_cake_order_view, name='admin_cake_order_view'),
    path('admin-panel/cake-orders/update/<int:order_id>/',
         views.admin_cake_order_update, name='admin_cake_order_update'),
    path('admin-panel/cake-orders/delete/<int:order_id>/',
         views.admin_cake_order_delete, name='admin_cake_order_delete'),
    path('admin-panel/packages/', views.admin_packages, name='admin_packages'),
    path('admin-panel/packages/add/',
         views.admin_package_add, name='admin_package_add'),
    path('admin-panel/packages/edit/<int:package_id>/',
         views.admin_package_edit, name='admin_package_edit'),
    path('admin-panel/packages/bulk-action/',
         views.admin_packages_bulk_action, name='admin_packages_bulk_action'),
    path('admin-panel/packages/delete/<int:package_id>/',
         views.admin_package_delete, name='admin_package_delete'),
    path('admin-panel/package-orders/',
         views.admin_package_orders, name='admin_package_orders'),
    path('admin-panel/package-orders/bulk-action/',
         views.admin_package_orders_bulk_action, name='admin_package_orders_bulk_action'),
    path('admin-panel/package-orders/view/<int:order_id>/',
         views.admin_package_order_view, name='admin_package_order_view'),
    path('admin-panel/package-orders/update/<int:order_id>/',
         views.admin_package_order_update, name='admin_package_order_update'),
    path('admin-panel/package-orders/delete/<int:order_id>/',
         views.admin_package_order_delete, name='admin_package_order_delete'),
    path('admin-panel/order-sales-report/',
         views.admin_order_sales_report, name='admin_order_sales_report'),
    path('admin-panel/stock-report/',
         views.admin_stock_report, name='admin_stock_report'),
    path('admin-panel/payments/', views.admin_payments, name='admin_payments'),
    path('admin-panel/payments/export/<str:file_format>/',
         views.admin_payments_export, name='admin_payments_export'),
    path('admin-panel/payments/bulk-action/',
         views.admin_payments_bulk_action, name='admin_payments_bulk_action'),
    path('admin-panel/payments/verify/<int:payment_id>/',
         views.admin_payment_verify, name='admin_payment_verify'),
    path('admin-panel/payments/delete/<int:payment_id>/',
         views.admin_payment_delete, name='admin_payment_delete'),
    path('admin-panel/testimonials/', views.admin_testimonials,
         name='admin_testimonials'),
    path('admin-panel/testimonials/bulk-action/',
         views.admin_testimonials_bulk_action, name='admin_testimonials_bulk_action'),
    path('admin-panel/testimonials/update/<int:testimonial_id>/',
         views.admin_testimonial_update, name='admin_testimonial_update'),
    path('admin-panel/testimonials/delete/<int:testimonial_id>/',
         views.admin_testimonial_delete, name='admin_testimonial_delete'),
    path('admin-panel/refunds/', views.admin_refunds, name='admin_refunds'),
    path('admin-panel/contact-inquiries/', views.admin_contact_inquiries,
         name='admin_contact_inquiries'),
    path('admin-panel/contact-inquiries/bulk-action/',
         views.admin_contact_inquiries_bulk_action, name='admin_contact_inquiries_bulk_action'),
    path('admin-panel/contact-inquiries/view/<int:inquiry_id>/',
         views.admin_contact_inquiry_view, name='admin_contact_inquiry_view'),
    path('admin-panel/contact-inquiries/reply/<int:inquiry_id>/',
         views.admin_contact_inquiry_reply, name='admin_contact_inquiry_reply'),
    path('admin-panel/contact-inquiries/update/<int:inquiry_id>/',
         views.admin_contact_inquiry_update, name='admin_contact_inquiry_update'),
    path('admin-panel/contact-inquiries/delete/<int:inquiry_id>/',
         views.admin_contact_inquiry_delete, name='admin_contact_inquiry_delete'),
    path('admin-panel/refunds/update/<int:refund_id>/',
         views.admin_refund_update, name='admin_refund_update'),
    path('admin-panel/activity-logs/', views.admin_activity_logs,
         name='admin_activity_logs'),
    path('admin-panel/activity-logs/export/<str:file_format>/',
         views.admin_activity_logs_export, name='admin_activity_logs_export'),
    path('admin-panel/activity-logs/print/',
         views.admin_activity_logs_print, name='admin_activity_logs_print'),
    path('admin-panel/activity-logs/bulk-action/',
         views.admin_activity_logs_bulk_action, name='admin_activity_logs_bulk_action'),
    path('admin-panel/activity-logs/delete/<int:log_id>/',
         views.admin_activity_log_delete, name='admin_activity_log_delete'),
    path('admin-panel/users/', views.admin_users, name='admin_users'),
    path('admin-panel/users/add/', views.admin_user_add, name='admin_user_add'),
    path('admin-panel/users/bulk-action/',
         views.admin_users_bulk_action, name='admin_users_bulk_action'),
    path('admin-panel/users/edit/<int:user_id>/',
         views.admin_user_edit, name='admin_user_edit'),
    path('admin-panel/users/view/<int:user_id>/',
         views.admin_user_view, name='admin_user_view'),
    path('admin-panel/users/password-reset/<int:user_id>/',
         views.admin_user_password_reset, name='admin_user_password_reset'),
    path('admin-panel/users/delete/<int:user_id>/',
         views.admin_user_delete, name='admin_user_delete'),
    path('admin-panel/users/role/<int:user_id>/',
         views.admin_user_role, name='admin_user_role'),
]
